### ISSUE TITLE
Remove analytics code

### ISSUE THREAD

**Issue by greatislander** [codelearncreate/c2lc-coding-environment#417]
Remove:

https://github.com/codelearncreate/c2lc-coding-environment/blob/b5a7846cf2240c471f1a51d2d31612e4214f5204/public/index.html#L24-L38

https://github.com/codelearncreate/c2lc-coding-environment/blob/b5a7846cf2240c471f1a51d2d31612e4214f5204/src/PrivacyModal.js#L65-L93

**Comment by sbates-idrc** [comment]
There will be some more work in addition to the code identified above: we also have a cookie notice that we display, that we would no longer need. This was the initial PR, with all the changes: https://github.com/codelearncreate/c2lc-coding-environment/pull/393/files
